name: Test

on: 
  pull_request: {}
  push:
    branches: "*"
    tags: "*"

jobs:
  self-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch images referenced in images.json
        run: python .github/workflows/get_openapi.py
          
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Update model registry
        env:
          ECR_REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.email "ci@pollinations.ai"
          git config --global user.name "pollinations-ci"
          git add . && (git commit -m "Fetched openapi.json for images referenced in: ${{ github.event.head_commit.message }}" && git push) || echo "model index not updated"